In [1]:
import numpy as np

In [20]:
# shapes must be same in order to perform operation simultaneously
a=np.arange(10).reshape(5,2)
b=np.arange(10,20,).reshape(5,2)

In [21]:

display(a)
display(b)
np.add(a,b)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

array([[10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28]])

In [37]:
display(np.concatenate((a,b),axis=1))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13],
       [ 4,  5, 14, 15],
       [ 6,  7, 16, 17],
       [ 8,  9, 18, 19]])

In [23]:
display(np.mean((a,b)))

9.5

In [24]:
display(np.median((a,b)))

9.5

In [25]:
display(np.cos(b))

array([[-0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678],
       [ 0.13673722, -0.75968791],
       [-0.95765948, -0.27516334],
       [ 0.66031671,  0.98870462]])

In [26]:
display(np.sin(b))

array([[-0.54402111, -0.99999021],
       [-0.53657292,  0.42016704],
       [ 0.99060736,  0.65028784],
       [-0.28790332, -0.96139749],
       [-0.75098725,  0.14987721]])

In [27]:
display(np.tan(a))

array([[ 0.        ,  1.55740772],
       [-2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501],
       [-0.29100619,  0.87144798],
       [-6.79971146, -0.45231566]])

In [28]:
display(np.std((a,b)))

5.766281297335398

In [44]:
c=np.arange(30,40).reshape(5,2)

In [55]:
a[0]=1
display(np.mod(c,a))

array([[0, 0],
       [0, 0],
       [2, 0],
       [0, 2],
       [6, 3]], dtype=int32)

In [56]:
display(np.where(c%2==1,10,30))

array([[30, 10],
       [30, 10],
       [30, 10],
       [30, 10],
       [30, 10]])

In [60]:
display(np.percentile(c,a))

array([[30.09, 30.09],
       [30.18, 30.27],
       [30.36, 30.45],
       [30.54, 30.63],
       [30.72, 30.81]])

In [68]:
display(np.stack((a,b)))
display(np.hstack((a,c)))
display(np.vstack((b,c)))

array([[[ 1,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

array([[ 1,  1, 30, 31],
       [ 2,  3, 32, 33],
       [ 4,  5, 34, 35],
       [ 6,  7, 36, 37],
       [ 8,  9, 38, 39]])

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [73]:
a.transpose()

array([[1, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [74]:
b.conjugate()

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [89]:
x=a.ravel()
x=x.reshape(2,5)
x.flatten()

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
d=np.arange(40,60).reshape(4,5)
d

array([[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [147]:
np.vsplit(d,4)

[array([[40, 41, 42, 43, 44]]),
 array([[45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54]]),
 array([[55, 56, 57, 58, 59]])]

In [148]:
np.hsplit(d,5)

[array([[40],
        [45],
        [50],
        [55]]),
 array([[41],
        [46],
        [51],
        [56]]),
 array([[42],
        [47],
        [52],
        [57]]),
 array([[43],
        [48],
        [53],
        [58]]),
 array([[44],
        [49],
        [54],
        [59]])]

In [152]:
np.argmax(a)

9